jobs:
    - job: update_all_app_manifests
      pool:
          vmImage: 'windows-2019'
      steps:
          - pwsh: Write-Output $env:BUILD_REPOSITORY_LOCALPATH
          - pwsh: Write-Output $env:BUILD_SOURCESDIRECTORY
          - pwsh: Write-Output $env:AGENT_BUILDDIRECTORY
          - pwsh: git clone https://github.com/lukesampson/scoop
            workingDirectory: ..\
          - pwsh: ls
          - pwsh: . ..\scoop\bin\checkver.ps1 -dir .
